.gitignore

Added .gitignore and the root folders

Initial project structure

---

.github/CODEOWNERS

Adding @ProgrammingPhilippines/progphilbotcore as the code owner for this repository to enable auto assignment of reviewer(s).

Add ProgPhilBotCore team as code owner

---

.github/workflows/gradle.yml
build.gradle

**Changes**
- Add `Javacord`
- Add `Dotenv`
- ~Add Gradle plugin for `dependencyCheck`~ _will use Dependabot instead_

Add dependencies

---

bot/cogs/announcements.py
bot/utils/modals.py

This pull introduces new command `/multi_with_media` 
* accepts an optional argument `photo` 
* the inputs are collected through modal 
#28 
* Hardware:
* Toolchain:
* SDK:

Multiline with media

---

bot/cogs/announcements.py
bot/config.py
bot/main.py
config.yml
poetry.lock
pyproject.toml

Added a configuration file (yaml), a "config.py" file (loads all the configs inside .yml file) so devs can import the configuration dataclasses from that file.
Example:
```py
from config import BotConfig
...
bot = ProgPhil()
bot.run(BotConfig.token)
```

Added configs and refactored announcement.py imports

---

.github/workflows/main.yml

Created Initial Github Actions, Currently checks for errors on bot directory.
python-version: ["3.10"]
poetry-version: ["1.3.2"]
Test was done on separate repository
* Hardware:
* Toolchain:
* SDK:

Github Action Workflow

---

.gitignore
bot/config.py
config.yml

Updated config file, and the configuration loader to load user-configs if it exists.
* Hardware:
* Toolchain:
* SDK:

Updated config file and config loader

---

bot/cogs/announcements.py
bot/cogs/error_handling.py

Created a error handler, this feature sends a feedback to user when an error occured during the execution of the command.
* Hardware:
* Toolchain:
* SDK:

Error handling

---

.dockerignore
.github/workflows/docker-ci.yml
README.md

added badges on readme. badges created based on this [docs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-event-parameter)
* Hardware:
* Toolchain:
* SDK:

Readme badges

---

Dockerfile

Renamed `PROGPHIL` arg into `token` due to arg variable being unable to consume on build. 
- [/] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [/] This change requires a documentation update
* Hardware:
* Toolchain:
* SDK:
- [/] My code follows the style guidelines of this project
- [/] I have performed a self-review of my code
- [/] I have commented my code, particularly in hard-to-understand areas

Updated Dockerfile for CD

---

bot/cogs/announcements.py

- Fixes a typo in the announcement.
* Hardware:
* Toolchain:
* SDK:

fix wether typo

---

.github/workflows/release.yml

Fix: just changed the dir to prod dir. normal bug fix.
* Hardware:
* Toolchain:
* SDK:

fix: changed dir to pph-prod/progphil-bot based in server.

---

.github/workflows/release.yml

fix: fixes issue for release action ssh error.  
* Hardware:
* Toolchain:
* SDK:

fix: fixed ssh private key variable name

---

bot/cogs/auto_responder.py
bot/database/auto_responder.py
bot/ui/views/announcement.py
bot/ui/views/auto_responder.py

Attempt to fix announcement mention bug
- Fixed announcement channel mentions acting up when selecting categories
- Removed categories from channel selections.
- Fixed delete command on auto responses when the entry count reached more than 25.
* Hardware:
* Toolchain:
* SDK:

fix: fixed announcement view channel mentions

---

bot/cogs/error_handling.py
bot/cogs/trivia.py
bot/config.py
config.yml

#83 
The bot now logs the unknown error logs to a specific channel
* Hardware:
* Toolchain:
* SDK:

enhancement: updated error handling, also included log channel

---

Dockerfile
poetry.lock
pyproject.toml

Implement changes on docker file to satisfy yoyo migrations requirement.
docker file was not updated properly because yoyo migrations failed during installation
added yoyo dependencies on dockerfile
docker file was build successfully on local and run

Add docker file dependencies, modify poerty toml

---

bot/cogs/define_word.py

fixed the issue when defining words prefixed with `/`
fixed error message when the API returns 404
* Hardware:
* Toolchain:
* SDK:

fix: fixed error on defining slash words

---

bot/cogs/currency_converter.py
bot/cogs/error_handling.py
bot/ui/views/currency_converter.py
migrations/6_currency_converter.sql

The exchange command converts the specified amount of currency from the source currency to the target currency using the external API. It also checks if the specified currencies are supported and if the command is enabled in the bot's configuration. If there is an error, it sends a message to the log channel.
The currencies command sends a list of supported currencies in a paginated view. The view has two buttons to navigate through the pages.
The toggle_config command toggles the currency converter feature on or off. It is only available to staff members, and it sends an ephemeral message to the user who used the command.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …

Currency converter

---

bot/cogs/define_word.py
bot/cogs/error_handling.py
bot/ui/views/define_word.py
migrations/7_define_word.sql

- refactored the code
- fixed the view bug
- some fixes
Fixes #121 
* Hardware:
* Toolchain:
* SDK:

Fix define

---

bot/cogs/forum_cleanup.py
bot/database/forum_cleanup.py
migrations/9_forum_cleanup.sql

Added a new feature: Auto forum closing
* Hardware:
* Toolchain:
* SDK:

feat: add forum auto closing

---

bot/cogs/forum_cleanup.py

Fixed forum cleanup check
Fixed check condition comparing between int and record object
* Hardware:
* Toolchain:
* SDK:

fix: fixed forum cleanup checks

---

bot/cogs/auto_tagging.py
bot/cogs/forum_cleanup.py
bot/database/forum_cleanup.py
migrations/9_forum_cleanup.sql

Removed thread locking and added custom message feature for thread closing
* Hardware:
* Toolchain:
* SDK:

chore: removed locking and added custom messages

---

bot/cogs/currency_converter.py
bot/cogs/error_handling.py

Fixed the issue where the box errors out when the input has quotes, also fixed the amount validation.
* Hardware:
* Toolchain:
* SDK:

fix: fixed quote errors and invalid amount inputs

---

bot/cogs/anonymous_posting.py
bot/cogs/currency_converter.py
bot/cogs/error_handling.py
bot/database/anonymous_posting.py
bot/ui/modals/anonymous_posting.py
bot/ui/views/anon_posting.py
migrations/10_anon_posting_view.sql

Added a setbutton command to make a persistent view
* Hardware:
* Toolchain:
* SDK:

enhancement: improved anon messages

---

bot/cogs/auto_responder.py
bot/database/auto_responder.py
bot/ui/modals/auto_responder.py
bot/ui/views/auto_responder.py
migrations/11_auto_responder_improvement.sql

Improved the Auto responder cog as specified
- created channel selection view
- updated database handler 
- implemented the changes
Auto responder improvements

Auto responder improvements

---

bot/ui/modals/anonymous_posting.py
bot/ui/views/anon_posting.py

Change message if anon post is from button
* Hardware:
* Toolchain:
* SDK:

chore: edit message on button

---

bot/cogs/dev_help.py

* Hardware:
* Toolchain:
* SDK:

chore: flip conditions

---

bot/cogs/dev_help.py
bot/cogs/user_reminder.py
bot/database/user_reminder.py
migrations/14_user_reminder.sql

Add the periodical reminder feature and fixed dev_help solver condition (AGAIN)
* Hardware:
* Toolchain:
* SDK:

Periodical reminder

---

.gitignore
bot/cogs/currency_converter.py

Fixes # 161
- Changed the string formatting and added additional functions inside the Converter cog to return the proper formatted currency.
* Hardware:
* Toolchain:
* SDK:

Changed string formatting for converting currency. Ticket#161

---

bot/cogs/currency_converter.py

Fixed locale issue when trying to convert currencies
* Hardware:
* Toolchain:
* SDK:

fix: reverted old formatting to fix locale issues

---

bot/cogs/forum_cleanup.py

Ignore pinned threads from getting cleaned up
* Hardware:
* Toolchain:
* SDK:

feat: ignore pinned threads from getting archived

---

bot/cogs/currency_converter.py

Fixed response data when collecting symbols at startup
* Hardware:
* Toolchain:
* SDK:

fix: fixed response

---

bot/cogs/dev_help.py
bot/database/dev_help.py
bot/ui/views/dev_help.py
migrations/17_dev_help_views.sql

Improve help-solver
Remove the commands /help-solver message and /help-solver tag and all associated actions to each
Replace the removed commands with /help-solver configure
Upon executing the /help-solver configure`, the admins must be able to define the forum where the auto-reply mark as solved will be applied, and the forum tag to be assigned to a post after marking it as solved
Restrict usage of the pph-solved prefix command to only be usable by mods and admins
The bot must automatically reply to every new dev-help post a clickable button component
The button must have the text "Mark this post as Solved!"
The button must only be clickable by the author of the post
The bot must pin the auto-replied button
The auto reply must come after all set auto response configurations
Upon clicking …

improvement: improved help-solver

---

bot/ui/views/dev_help.py

Add optional selection for users that helped solve a dev-help problem
* Hardware:
* Toolchain:
* SDK:

improvement: add user selection after solve

---

.env.example

add missing env variable from **.env.example** that is required to setup
* Hardware:
* Toolchain:
* SDK:

fix: add missing env variable

---

bot/cogs/welcome.py
bot/database/welcome.py

Fixes #179
/bot/cogs/welcome.py line 24 - 60
```python
@Cog.listener()
async def on_member_update(self, before: Member, after: Member):
"""
An event listener that triggers when a member's information is updated.
Parameters:
- before (Member): The member object before the update.
- after (Member): The member object after the update.
"""
channel_id = await self.settings.get_setting("welcome_channel")
if channel_id == 0:
return
channel = after.guild.get_channel(channel_id)
if channel is None:
return
member_flags_before: MemberFlags = before.flags
member_flags_after: MemberFlags = after.flags
if (
not member_flags_before.completed_onboarding
and member_flags_after.completed_onboarding
):
result = await self.db.get_message()
if result is None: …
```

Updated welcomer to work on new onboarding process

---

bot/cogs/auto_responder.py

Add matching type to /responder all
* Hardware:
* Toolchain:
* SDK:

chore: add matching type for /responder all

---

bot/ui/views/auto_responder.py

* Hardware:
* Toolchain:
* SDK:

fix: fixed _format_description

---

bot/cogs/welcome.py

I changed the mismatched variable names
1. Manual Testing

bugfix: fixed variable name mismatch

---

bot/cogs/currency_converter.py

feat: update currency formatting

---

bot/cogs/dev_help.py
bot/ui/views/dev_help.py

* Hardware:
* Toolchain:
* SDK:

fix: truncate title

---

bot/cogs/welcome.py

I made a spelling mistake on a timedelta function in welcomer feature

Bug Fix: Mispelled variable in timedelta function

---

bot/cogs/auto_tagging.py
bot/ui/views/post_assist.py

* Hardware:
* Toolchain:
* SDK:

chore: made edit command ephemeral

---

bot/cogs/error_handling.py
bot/ui/views/dev_help.py

Add an extra API call if the thread is not in the internal cache.
* Hardware:
* Toolchain:
* SDK:

fix: fetch threads if it's not in cache

---

bot/config.py
bot/main.py

* Hardware:
* Toolchain:
* SDK:

chore: add port to config

---

bot/main.py

* Hardware:
* Toolchain:
* SDK:

fix: add default value to port

---

bot/utils/logger.py

Changed formatting for discord and console loggers

Changed logger formatting

---

.github/workflows/release.yml

Update the googleapi release-please-action used in the pipeline

Update release-please-action reference

---

.github/workflows/release.yml

* Hardware:
* Toolchain:
* SDK:

Update for merging

---

.github/workflows/pylint-checks.yml

* Hardware:
* Toolchain:
* SDK:

Add on push branches

---

.github/workflows/pylint-checks.yml
.github/workflows/release-on-merge.yml

* Hardware:
* Toolchain:
* SDK:

Add workflow filters

---

.github/workflows/release-on-merge.yml

Automatically update the project version before deployment using the release-please action

Automatic project versioning

---

src/cogs/forum/forum_showcase.py

This should fix the first response of the config command to be ephemeral.
Fixes #267 
* Hardware:
* Toolchain:
* SDK:

[FIX] Select target channel not ephemeral
